### ISSUE TITLE
BE: Signup / Login OAuth2

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-vampire#14]
* https://developers.google.com/calendar/quickstart/js
* https://developers.google.com/calendar/quickstart/python
* https://cloud.google.com/nodejs/getting-started/authenticate-users
* https://dev.to/risafj/beginner-s-guide-to-oauth-understanding-access-tokens-and-authorization-codes-2988

---------- 
* Create User when authentication is success 
* Save access token as session

**Comment by blacksector** [comment]
@singhmi4 this might be helpful: https://gist.github.com/blacksector/4f6f40537a9a5c7d4aed647f76168988 when setting the endpoint URIs on Google Developer console you would want to set them as:
- http://localhost:5000/login
- http://localhost:5000/authorize

This is a super simplified version of authentication and the library I used was [authlib](https://docs.authlib.org/en/latest/)

I will be pushing the token data into the session as well which you don't need to do, I'll be pushing changes hopefully tonight or tomorrow with the database models and controllers so that you can see how the DB looks!

**Comment by singhmi4** [comment]
I think this PR is not needed since it's now being implemented through the front-end in PR: #19

**Comment by singhmi4** [comment]
Taken care of in different issue. #47
